import pygame


STANDARD = 'standard'
LAYOUTS = {STANDARD: 0}
FPS = 60
TILESIZE = 40
HOR_TILES = 11
VER_TILES = 11
ARENAWIDTH = TILESIZE * HOR_TILES
ARENAHEIGHT = TILESIZE * VER_TILES
WINWIDTH = ARENAWIDTH
WINHEIGHT = ARENAHEIGHT

UP, RIGHT, LEFT, DOWN, BOMB = range(5)
PLAYER1, PLAYER2, PLAYER3, PLAYER4 = range(4)
X, Y = range(2)
HOR_AXIS, VER_AXIS = range(2)
JOYAXISTOLERANCE = 0.9
KEYBOARD_CONTROLS = {PLAYER1: {UP: pygame.K_w,  RIGHT: pygame.K_d,     LEFT: pygame.K_a,    DOWN: pygame.K_s,
                     BOMB: pygame.K_f},
                     PLAYER2: {UP: pygame.K_UP, RIGHT: pygame.K_RIGHT, LEFT: pygame.K_LEFT, DOWN: pygame.K_DOWN,
                     BOMB: pygame.K_m}}
JOYSTICK_CONTROLS = {PLAYER1: {HOR_AXIS: 6, VER_AXIS: 7, BOMB: 14},
                     PLAYER2: {HOR_AXIS: 2, VER_AXIS: 3, BOMB: 2}}
SOFTSPAWNCHANCE = 0.85
POWERUPSPAWNCHANCE = 0.25
PLAYERSPAWNLOCATION = {PLAYER1: {X: TILESIZE * 1, Y: TILESIZE * 1},
                       PLAYER2: {X: ARENAWIDTH - TILESIZE * 2, Y: ARENAHEIGHT - TILESIZE * 2}}
TOTPOWERUPS = 3
EXTRABOMB, EXTRASPEED, EXTRARANGE = range(TOTPOWERUPS)